/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zhh_test_jdk_NativeTest */

#ifndef _Included_com_zhh_test_jdk_NativeTest
#define _Included_com_zhh_test_jdk_NativeTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * javac com/zhh/test/Hi.java -h .
 * Class:     com_zhh_test_jdk_NativeTest
 * Method:    sum
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_zhh_test_jdk_NativeTest_sum
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
